//JOption pane is contained in the package javax.swing
import javax.swing.*;

public class guessing__game {
    public static void main(String[] args){
        //The computer number generates a whole and random number i a range of 1 to 100
        int computerNumber = (int)Math.round(Math.random()*100);
        //answer generated by the user is set to 0
        int userAnswer = 0 ;
        //prints the computer generated value
        System.out.println("The correct guess would be: " + computerNumber);
        int count  = 1;

        while (userAnswer!=computerNumber)
        {
            //JOptionPane has four parameters parent Component ,message to be printed,title and the message type

            String response  = JOptionPane.showInputDialog(null,"Enter the guess between 1 and 100" , "guessing game " , 3);
            userAnswer = Integer.parseInt(response);
            JOptionPane.showMessageDialog(null,"" + determineGuess(userAnswer,computerNumber,count));
            count++ ;

        }
    }
    public static String determineGuess(int userAnswer , int computerNumber,int count){
        if(userAnswer <=0 || userAnswer > 100){
            return "your guess is invalid";
        }
        else if(userAnswer == computerNumber){
            return "correct!\nTotal Guesses : " +count ;

        }
        else if (userAnswer > computerNumber){
            return "Your guess is too high,try again.\n Try number : " + count ;
        }
        else if (userAnswer < computerNumber){
            return "Your guess is too low , try again.\n Try Number : " + count ;
        }
        else {
            return "Your guess is incorrectly\n try Number : " + count ;
        }

    }

}
